version: '3.7'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    container_name: php-fpm
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    environment:
      - TZ=Asia/Taipei
